// Inlined copies of ../examples/*.js, so the web editor works standalone
// (no fetch, no server needed) even when opened straight from disk.
// Generated by scripts/sync-examples.js - do not edit by hand, edit the
// files in examples/ instead and re-run: node scripts/sync-examples.js

window.TEXTMODE_EXAMPLES = [
  {
    name: "plasma",
    label: "Plasma",
    code:
"// Classic \"plasma\" demo effect: a handful of sine waves summed together\n" +
"// and mapped to an ascii ramp and a color band.\n" +
"\n" +
"var CHARS = ' .:-=+*#%@';\n" +
"var PALETTE = ['blue', 'cyan', 'green', 'yellow', 'red', 'magenta'];\n" +
"\n" +
"function value() {\n" +
"  var time = frame / fps;\n" +
"  var v = Math.sin(x * 0.2 + time) +\n" +
"          Math.sin(y * 0.15 + time * 1.3) +\n" +
"          Math.sin((x + y) * 0.1 + time * 0.7) +\n" +
"          Math.sin(Math.sqrt(x * x + y * y) * 0.1 - time);\n" +
"\n" +
"  return (v + 4) / 8; // normalize roughly to 0..1\n" +
"}\n" +
"\n" +
"function char() {\n" +
"  var v = value();\n" +
"  var index = Math.floor(v * (CHARS.length - 1));\n" +
"  return CHARS.charAt(index);\n" +
"}\n" +
"\n" +
"function fg() {\n" +
"  var v = value();\n" +
"  var index = Math.floor(v * (PALETTE.length - 1));\n" +
"  return PALETTE[index];\n" +
"}\n" +
"\n" +
"exports.char = char;\n" +
"exports.fg = fg;\n"
  },
  {
    name: "rain",
    label: "Digital rain",
    code:
"// Matrix-style digital rain. Uses the \"frame\" style since each column\n" +
"// needs to remember its own drop position and speed between frames -\n" +
"// state that a stateless per-cell char()/fg() pair can't hold on its own.\n" +
"\n" +
"var CHARS = '01ABCDEFGHIJKLMNOPQRSTUVWXYZ';\n" +
"var TRAIL_LENGTH = 12;\n" +
"\n" +
"var drops = null;\n" +
"var lastCols = 0;\n" +
"\n" +
"function randomChar() {\n" +
"  var index = Math.floor(Math.random() * CHARS.length);\n" +
"  return CHARS.charAt(index);\n" +
"}\n" +
"\n" +
"function setup(cols, rows) {\n" +
"  var i;\n" +
"\n" +
"  drops = [];\n" +
"\n" +
"  for (i = 0; i < cols; i++) {\n" +
"    drops.push({\n" +
"      y: -Math.floor(Math.random() * rows),\n" +
"      speed: 0.3 + Math.random() * 0.7\n" +
"    });\n" +
"  }\n" +
"\n" +
"  lastCols = cols;\n" +
"}\n" +
"\n" +
"exports.frame = function (grid) {\n" +
"  var x, y, drop, headY, dist, cell;\n" +
"\n" +
"  if (drops === null || lastCols !== width) {\n" +
"    setup(width, height);\n" +
"  }\n" +
"\n" +
"  for (y = 0; y < height; y++) {\n" +
"    for (x = 0; x < width; x++) {\n" +
"      grid[y][x].ch = ' ';\n" +
"      grid[y][x].fg = 'default';\n" +
"    }\n" +
"  }\n" +
"\n" +
"  for (x = 0; x < width; x++) {\n" +
"    drop = drops[x];\n" +
"    drop.y += drop.speed;\n" +
"\n" +
"    if (drop.y - TRAIL_LENGTH > height) {\n" +
"      drop.y = -Math.floor(Math.random() * height);\n" +
"      drop.speed = 0.3 + Math.random() * 0.7;\n" +
"    }\n" +
"\n" +
"    headY = Math.floor(drop.y);\n" +
"\n" +
"    for (y = 0; y < height; y++) {\n" +
"      dist = headY - y;\n" +
"\n" +
"      if (dist < 0 || dist > TRAIL_LENGTH) {\n" +
"        continue;\n" +
"      }\n" +
"\n" +
"      cell = grid[y][x];\n" +
"      cell.ch = randomChar();\n" +
"      cell.fg = dist === 0 ? 'brightwhite' : 'green';\n" +
"    }\n" +
"  }\n" +
"};\n"
  },
  {
    name: "life",
    label: "Conway's Life",
    code:
"// Conway's Game of Life. Needs to look at each cell's neighbors, so it\n" +
"// keeps its own grid (wrapped at the edges) and only uses the \"frame\"\n" +
"// buffer as an output sink.\n" +
"\n" +
"var cells = null;\n" +
"var next = null;\n" +
"var lastCols = 0;\n" +
"var lastRows = 0;\n" +
"var STEP_EVERY_N_FRAMES = 3;\n" +
"\n" +
"function setup(cols, rows) {\n" +
"  var x, y;\n" +
"\n" +
"  cells = [];\n" +
"  next = [];\n" +
"\n" +
"  for (y = 0; y < rows; y++) {\n" +
"    cells.push([]);\n" +
"    next.push([]);\n" +
"    for (x = 0; x < cols; x++) {\n" +
"      cells[y].push(Math.random() < 0.2 ? 1 : 0);\n" +
"      next[y].push(0);\n" +
"    }\n" +
"  }\n" +
"\n" +
"  lastCols = cols;\n" +
"  lastRows = rows;\n" +
"}\n" +
"\n" +
"function countNeighbors(x, y, cols, rows) {\n" +
"  var count = 0;\n" +
"  var dx, dy, nx, ny;\n" +
"\n" +
"  for (dy = -1; dy <= 1; dy++) {\n" +
"    for (dx = -1; dx <= 1; dx++) {\n" +
"      if (dx === 0 && dy === 0) {\n" +
"        continue;\n" +
"      }\n" +
"      nx = (x + dx + cols) % cols;\n" +
"      ny = (y + dy + rows) % rows;\n" +
"      count += cells[ny][nx];\n" +
"    }\n" +
"  }\n" +
"\n" +
"  return count;\n" +
"}\n" +
"\n" +
"function step(cols, rows) {\n" +
"  var x, y, alive, neighbors, willLive, tmp;\n" +
"\n" +
"  for (y = 0; y < rows; y++) {\n" +
"    for (x = 0; x < cols; x++) {\n" +
"      alive = cells[y][x];\n" +
"      neighbors = countNeighbors(x, y, cols, rows);\n" +
"      willLive = alive ? (neighbors === 2 || neighbors === 3) : (neighbors === 3);\n" +
"      next[y][x] = willLive ? 1 : 0;\n" +
"    }\n" +
"  }\n" +
"\n" +
"  tmp = cells;\n" +
"  cells = next;\n" +
"  next = tmp;\n" +
"}\n" +
"\n" +
"exports.frame = function (grid) {\n" +
"  var x, y, cell;\n" +
"\n" +
"  if (cells === null || lastCols !== width || lastRows !== height) {\n" +
"    setup(width, height);\n" +
"  }\n" +
"\n" +
"  if (frame % STEP_EVERY_N_FRAMES === 0) {\n" +
"    step(width, height);\n" +
"  }\n" +
"\n" +
"  for (y = 0; y < height; y++) {\n" +
"    for (x = 0; x < width; x++) {\n" +
"      cell = grid[y][x];\n" +
"      if (cells[y][x]) {\n" +
"        cell.ch = '#';\n" +
"        cell.fg = 'brightwhite';\n" +
"      } else {\n" +
"        cell.ch = ' ';\n" +
"        cell.fg = 'default';\n" +
"      }\n" +
"    }\n" +
"  }\n" +
"};\n"
  },
  {
    name: "fire",
    label: "Fire",
    code:
"// The classic \"Doom fire\" cellular automaton: heat rises from the\n" +
"// bottom row, decaying and drifting sideways at random as it goes.\n" +
"// Uses \"frame\" because each cell's next heat depends on the cell below it.\n" +
"\n" +
"var heat = null;\n" +
"var lastCols = 0;\n" +
"var lastRows = 0;\n" +
"\n" +
"var PALETTE = [\n" +
"  { ch: ' ', fg: 'default' },\n" +
"  { ch: '.', fg: 'red' },\n" +
"  { ch: ':', fg: 'red' },\n" +
"  { ch: '+', fg: 'red' },\n" +
"  { ch: '*', fg: 'yellow' },\n" +
"  { ch: '%', fg: 'yellow' },\n" +
"  { ch: '#', fg: 'brightyellow' },\n" +
"  { ch: '@', fg: 'brightwhite' }\n" +
"];\n" +
"\n" +
"function setup(cols, rows) {\n" +
"  var x, y;\n" +
"\n" +
"  heat = [];\n" +
"\n" +
"  for (y = 0; y < rows; y++) {\n" +
"    heat.push([]);\n" +
"    for (x = 0; x < cols; x++) {\n" +
"      heat[y].push(0);\n" +
"    }\n" +
"  }\n" +
"\n" +
"  lastCols = cols;\n" +
"  lastRows = rows;\n" +
"}\n" +
"\n" +
"exports.frame = function (grid) {\n" +
"  var x, y, src, decay, level, spread, cell, paletteEntry;\n" +
"\n" +
"  if (heat === null || lastCols !== width || lastRows !== height) {\n" +
"    setup(width, height);\n" +
"  }\n" +
"\n" +
"  for (x = 0; x < width; x++) {\n" +
"    heat[height - 1][x] = PALETTE.length - 1;\n" +
"  }\n" +
"\n" +
"  for (y = 0; y < height - 1; y++) {\n" +
"    for (x = 0; x < width; x++) {\n" +
"      src = heat[y + 1][x];\n" +
"      decay = Math.floor(Math.random() * 3);\n" +
"      level = src - decay;\n" +
"      if (level < 0) {\n" +
"        level = 0;\n" +
"      }\n" +
"\n" +
"      spread = x + Math.floor(Math.random() * 3) - 1;\n" +
"      if (spread < 0) {\n" +
"        spread = 0;\n" +
"      }\n" +
"      if (spread > width - 1) {\n" +
"        spread = width - 1;\n" +
"      }\n" +
"\n" +
"      heat[y][spread] = level;\n" +
"    }\n" +
"  }\n" +
"\n" +
"  for (y = 0; y < height; y++) {\n" +
"    for (x = 0; x < width; x++) {\n" +
"      level = heat[y][x];\n" +
"      if (level > PALETTE.length - 1) {\n" +
"        level = PALETTE.length - 1;\n" +
"      }\n" +
"\n" +
"      paletteEntry = PALETTE[level];\n" +
"      cell = grid[y][x];\n" +
"      cell.ch = paletteEntry.ch;\n" +
"      cell.fg = paletteEntry.fg;\n" +
"    }\n" +
"  }\n" +
"};\n"
  },
  {
    name: "flow",
    label: "Flow",
    code:
"// ---------------------\n" +
"// flow thingy by pck404\n" +
"// ---------------------\n" +
"\n" +
"var CHARS = '//o\\\\\\\\//o';\n" +
"var PALETTE = [\n" +
"  203,\n" +
"  163,\n" +
"  48,\n" +
"  208,\n" +
"  177,\n" +
"  227\n" +
"];\n" +
"\n" +
"function value(px, py) {\n" +
"  return 0.5 + noise(frame / 500, x / 20, y / 5) / 2;\n" +
"}\n" +
"\n" +
"exports.char = () => {\n" +
"  var v = (1 + value(x, y)) % 1;\n" +
"  var index = Math.floor(v * (CHARS.length - 1));\n" +
"  return CHARS.charAt(index);\n" +
"}\n" +
"\n" +
"exports.fg = () => {\n" +
"  var v = (1 + value(x, y)) % 1;\n" +
"  var index = Math.floor(v * (PALETTE.length - 1));\n" +
"  return PALETTE[index];\n" +
"}\n" +
"\n" +
"exports.bg = () => {\n" +
"  var v = 0.5 + noise(frame / 120, x / 40, y / 20) / 2;\n" +
"  return v > 0.5 ? 16 : 17;\n" +
"}\n" +
"\n" +
"// --------------------------------------------------------\n" +
"\n" +
"// Port of Ken Perlin's improved noise reference implementation — 3D only.\n" +
"// Original: https://cs.nyu.edu/~perlin/noise/ (ImprovedNoise.java)\n" +
"\n" +
"function fade(t) {\n" +
"  return t * t * t * (t * (t * 6 - 15) + 10);\n" +
"}\n" +
"\n" +
"function lerp(t, a, b) {\n" +
"  return a + t * (b - a);\n" +
"}\n" +
"\n" +
"function grad(hash, x, y, z) {\n" +
"  var h = hash & 15;\n" +
"  var u = h < 8 ? x : y;\n" +
"  var v = h < 4 ? y : (h === 12 || h === 14 ? x : z);\n" +
"  return ((h & 1) === 0 ? u : -u) + ((h & 2) === 0 ? v : -v);\n" +
"}\n" +
"\n" +
"var permutation = [\n" +
"  151, 160, 137, 91, 90, 15,\n" +
"  131, 13, 201, 95, 96, 53, 194, 233, 7, 225, 140, 36, 103, 30, 69, 142, 8, 99, 37, 240, 21, 10, 23,\n" +
"  190, 6, 148, 247, 120, 234, 75, 0, 26, 197, 62, 94, 252, 219, 203, 117, 35, 11, 32, 57, 177, 33,\n" +
"  88, 237, 149, 56, 87, 174, 20, 125, 136, 171, 168, 68, 175, 74, 165, 71, 134, 139, 48, 27, 166,\n" +
"  77, 146, 158, 231, 83, 111, 229, 122, 60, 211, 133, 230, 220, 105, 92, 41, 55, 46, 245, 40, 244,\n" +
"  102, 143, 54, 65, 25, 63, 161, 1, 216, 80, 73, 209, 76, 132, 187, 208, 89, 18, 169, 200, 196,\n" +
"  135, 130, 116, 188, 159, 86, 164, 100, 109, 198, 173, 186, 3, 64, 52, 217, 226, 250, 124, 123,\n" +
"  5, 202, 38, 147, 118, 126, 255, 82, 85, 212, 207, 206, 59, 227, 47, 16, 58, 17, 182, 189, 28, 42,\n" +
"  223, 183, 170, 213, 119, 248, 152, 2, 44, 154, 163, 70, 221, 153, 101, 155, 167, 43, 172, 9,\n" +
"  129, 22, 39, 253, 19, 98, 108, 110, 79, 113, 224, 232, 178, 185, 112, 104, 218, 246, 97, 228,\n" +
"  251, 34, 242, 193, 238, 210, 144, 12, 191, 179, 162, 241, 81, 51, 145, 235, 249, 14, 239, 107,\n" +
"  49, 192, 214, 31, 181, 199, 106, 157, 184, 84, 204, 176, 115, 121, 50, 45, 127, 4, 150, 254,\n" +
"  138, 236, 205, 93, 222, 114, 67, 29, 24, 72, 243, 141, 128, 195, 78, 66, 215, 61, 156, 180\n" +
"];\n" +
"\n" +
"var p = new Array(512);\n" +
"(function () {\n" +
"  var i;\n" +
"  for (i = 0; i < 256; i++) {\n" +
"    p[256 + i] = p[i] = permutation[i];\n" +
"  }\n" +
"})();\n" +
"\n" +
"function noise(x, y, z) {\n" +
"  var X = Math.floor(x) & 255;\n" +
"  var Y = Math.floor(y) & 255;\n" +
"  var Z = Math.floor(z) & 255;\n" +
"  x -= Math.floor(x);\n" +
"  y -= Math.floor(y);\n" +
"  z -= Math.floor(z);\n" +
"  var u = fade(x);\n" +
"  var v = fade(y);\n" +
"  var w = fade(z);\n" +
"  var A = p[X] + Y, AA = p[A] + Z, AB = p[A + 1] + Z;\n" +
"  var B = p[X + 1] + Y, BA = p[B] + Z, BB = p[B + 1] + Z;\n" +
"\n" +
"  return lerp(w, lerp(v, lerp(u, grad(p[AA], x, y, z),\n" +
"                                 grad(p[BA], x - 1, y, z)),\n" +
"                         lerp(u, grad(p[AB], x, y - 1, z),\n" +
"                                 grad(p[BB], x - 1, y - 1, z))),\n" +
"                 lerp(v, lerp(u, grad(p[AA + 1], x, y, z - 1),\n" +
"                                 grad(p[BA + 1], x - 1, y, z - 1)),\n" +
"                         lerp(u, grad(p[AB + 1], x, y - 1, z - 1),\n" +
"                                 grad(p[BB + 1], x - 1, y - 1, z - 1))));\n" +
"}\n"
  },
  {
    name: "ripple",
    label: "Ripple",
    code:
"// ----------------------\n" +
"// Water ripple by pck404\n" +
"// ----------------------\n" +
"\n" +
"var lastCols = 0;\n" +
"var lastRows = 0;\n" +
"\n" +
"var previous = null;\n" +
"var current = null;\n" +
"var next = null;\n" +
"\n" +
"var DAMP = 0.9;\n" +
"\n" +
"function buildGrid() {\n" +
"  var grid = [];\n" +
"  \n" +
"  for (let y = 0; y < height; ++y) {\n" +
"    let row = [];\n" +
"      \n" +
"    for (let x = 0; x < width; ++x) {\n" +
"      row.push(0);\n" +
"    }\n" +
"      \n" +
"    grid.push(row);\n" +
"  }\n" +
"  \n" +
"  return grid;\n" +
"  \n" +
"}\n" +
"\n" +
"exports.frame = function (grid) {\n" +
"  if (current == null || previous == null || next == null) {\n" +
"    current = buildGrid();\n" +
"    previous = buildGrid();\n" +
"    next = buildGrid();\n" +
"  }\n" +
"  \n" +
"  if (frame % 10 == 0) {\n" +
"    const edge = Math.min(width, height) / 5;\n" +
"    let x = edge + Math.floor(Math.random() * (width - 2 * edge));\n" +
"    let y = edge + Math.floor(Math.random() * (height - 2 * edge));\n" +
"    \n" +
"    const r = 5;\n" +
"\n" +
"    for (let dy = -r; dy <= r; dy++) {\n" +
"      for (let dx = -r; dx <= r; dx++) {\n" +
"        let xx = x + dx;\n" +
"        let yy = y + dy;\n" +
"\n" +
"        if (xx < 0 || xx >= width || yy < 0 || yy >= height)\n" +
"          continue;\n" +
"\n" +
"        let d2 = dx*dx + dy*dy;\n" +
"        current[yy][xx] += 0.4 * Math.exp(-d2 / 2);\n" +
"      }\n" +
"    }\n" +
"  }\n" +
"  \n" +
"  for (let y = 0; y < height; ++y) {\n" +
"    const row = current[y];\n" +
"    \n" +
"    for (let x = 0; x < width; ++x) {\n" +
"      let left = x == 0 ? 0 : row[x - 1];\n" +
"      let right = x == width - 1 ? 0 : row[x + 1];\n" +
"      let up = y == 0 ? 0 : current[y - 1][x];\n" +
"      let down = y == height - 1 ? 0 : current[y + 1][x];\n" +
"      let prev = previous[y][x];\n" +
"      let ul = (x == 0 || y == 0) ? 0 : current[y - 1][x - 1];\n" +
"      let ur = (x == width - 1 || y == 0) ? 0 : current[y - 1][x + 1];\n" +
"      let dl = (x == 0 || y == height - 1) ? 0 : current[y + 1][x - 1];\n" +
"      let dr = (x == width - 1 || y == height - 1) ? 0 : current[y + 1][x + 1];\n" +
"      \n" +
"      let sum = left + right + up + down + 0.707 * (ul + ur + dl + dr);\n" +
"\t\t\tnext[y][x] = (sum / (4 + 4 * 0.707) * 2 - prev) * DAMP;\n" +
"      \n" +
"      let edge = Math.min(x, y, width-1-x, height-1-y);\n" +
"      let absorb = Math.min(1, edge / Math.min(12, width/5, height/5));\n" +
"      absorb *= absorb;\n" +
"\n" +
"      next[y][x] *= absorb;\n" +
"    }\n" +
"  }\n" +
"  \n" +
"  \n" +
"  for (y = 0; y < height; y++) {\n" +
"    for (x = 0; x < width; x++) {\n" +
"      const cell = grid[y][x];\n" +
"      \n" +
"      const left = x == 0 ? 0 : current[y][x - 1];\n" +
"      const right = x == width - 1 ? 0 : current[y][x + 1];\n" +
"      const down = y == 0 ? 0 : current[y - 1][x];\n" +
"      const up = y == height - 1 ? 0 : current[y + 1][x];\n" +
"      const gx = right - left;\n" +
"      const gy = down - up;\n" +
"\n" +
"      const v = Math.sqrt(gx*gx + gy*gy);\n" +
"\n" +
"      const chars = \" .:-=+*#%@\";\n" +
"\n" +
"      const a = Math.min(1, Math.abs(v) * 8);\n" +
"      const i = Math.floor(a * (chars.length - 1));\n" +
"\n" +
"cell.ch = chars[i];\n" +
"      \n" +
"      cell.fg = 7;\n" +
"      cell.bg = 4;\n" +
"    }\n" +
"  }\n" +
"  \n" +
"  const tmp = previous\n" +
"  previous = current;\n" +
"  current = next;\n" +
"  next = tmp;\n" +
"};\n"
  }
];
